version: '3'

services:
  comex-api:
    container_name: comex-api
    restart: on-failure
    build:
      context: .
    volumes:
      - .:/myapp
    ports:
      - "9489:4012"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  communex-api:
    container_name: communex-api
    restart: on-failure
    image: mos4ic/communex-api:latest
    ports:
      - "9488:7860"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
