version: '3'

services:
  comex-api:
    container_name: comex-api
    restart: on-failure
    build:
      dockerfile: DockerfileApi
      context: .
    volumes:
      - .:/myapp
    ports:
      - "9489:4012"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - comex-redis

  comex-updater:
    container_name: comex-updater
    restart: on-failure
    build:
      dockerfile: DockerfileUpdater
      context: .
    volumes:
      - .:/myapp
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - comex-redis

  communex-api:
    container_name: communex-api
    restart: on-failure
    image: mos4ic/communex-api:latest
    ports:
      - "9488:7860"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  comex-redis:
    container_name: comex-redis
    image: redis:latest
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
