import { FastifyReply, FastifyRequest } from 'fastify'
import { STANDARD } from '../constants/code'

export async function getSubnet(request: FastifyRequest, reply: FastifyReply) {
  reply.status(STANDARD.SUCCESS).send({
    data: {
      id: 1,
      name: 'Prompting',
      activeKeys: 256,
      totalKeys: 256,
      activeValidators: 64,
      totalValidators: 64,
      activeMiners: 64,
      totalMiners: 64,
      registerCost: 100,

      githubUrl: 'https://github.com/commune/commune',
      registeredAt: '2021-08-01T00:00:00Z',
      registeredBy: '5hxxxxxxx',
      emissionPercentage: 5.31,

      modules: [
        {
          uid: 1,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 2,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 3,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 4,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },

        {
          uid: 5,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 6,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 7,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
        {
          uid: 8,
          key: '5kxxxxxxxxxx',
          emission: 0,
          incentive: 0,
          dividends: 0,
          delegation_fee: 0,
          stake: 0,
          address: '5ffff',
          active: true,
          in_immunity: true,
        },
      ],

      params: {
        immunityPeriod: 800,
        immunityPeriod2: 800,
        immunityPeriod3: 800,
        immunityPeriod4: 800,
        immunityPeriod5: 800,
        immunityPeriod6: 800,
      },
    },
  })
}
