name: Dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build task
        run: pnpm build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /data/comex-api
          remote_host: 20.212.6.4
          remote_port: 2222
          remote_user: why
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: 20.212.6.4
          port: 2222
          username: why
          key: ${{ secrets.DEPLOY_KEY }}
          script: cd /data/comex-api && docker compose pull && docker compose -f docker-compose.yml up -d --no-deps --build
