name: Prod

on:
  workflow_dispatch:
  push:
    tags:        
      - '**'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Pulling latest images
        run: docker compose pull
      
      - name: Build and start app
        run: docker compose up -d --no-deps --build